### ISSUE TITLE
View has incorrect orientation when app is in landscape mode

### ISSUE THREAD

**Issue by slava-v** [wimagguc/ios-custom-alertview#66] opened 2015-04-07 07:39 UTC
When app opens in landscape mode the view is shown in portrait mode
![sample](http://i.imgur.com/QL47YyR.png)
The custom view is a UITextView

**Comment by snakew79** [comment] 2015-04-07 10:41
Thank you very much for your newer version 0.9.
I confirm the issue. We have a tableview in the alert dialog.
When you make appear the dialog in portrait mode, dialog is shown correctly, as you can see in the following picture:
![schermata 2015-04-07 alle 12 29 29](https://cloud.githubusercontent.com/assets/11833620/7021461/13c7e518-dd22-11e4-8e5a-55498fb093da.png)
When I rotate the screen, also the dialog rotates correctly:
![schermata 2015-04-07 alle 12 29 41](https://cloud.githubusercontent.com/assets/11833620/7021486/32469a48-dd22-11e4-95e6-aaac9eb0ca1f.png)

But when I'm already in landscape mode and I activate the dialog, it occurs a wrong visualization:
![schermata 2015-04-07 alle 12 30 14](https://cloud.githubusercontent.com/assets/11833620/7021496/4c05f6fe-dd22-11e4-9c3a-7c6ef3eb90d4.png)
That's terrible when I rotate the phone again.
![schermata 2015-04-07 alle 12 30 28](https://cloud.githubusercontent.com/assets/11833620/7021503/6342bb5e-dd22-11e4-81ec-e5a1f80444b5.png)

Please fix this issue, it's very important for us.
Thank you for your job!

**Comment by wimagguc** [comment] 2015-04-07 13:11
Aww I see this, thanks. Will fix it asap.

**Comment by snakew79** [comment] 2015-04-07 13:43
also I forgot to say that the problem is only on iOS 8. In iOS 7 the alert dialog works correctly.
Thank you again

**Comment by wimagguc** [comment] 2015-04-07 15:56
I just released a fix for this in 6ad951cbd015065ba28897c9328ffbdbc141c091. Can you confirm that it works? Thanks again for spotting this bug.

**Comment by snakew79** [comment] 2015-04-07 16:07
Dear Richard,
I tested your last version and I confirm that bug is solved.
Thank you very much for your immediate reply! Keep up the good work!

**Comment by wimagguc** [comment] 2015-04-07 16:24
Thanks @snakew79 :)

**Closed by wimagguc** 2015-04-07 16:24 UTC
